import type { PatientCardPayload } from "./types";

export const demoPayload: PatientCardPayload = {
  version: 1,
  purpose: "itinerary",
  generatedAt: "2026-06-19T12:00:00.000Z",
  expiresAt: "2026-06-19T13:00:00.000Z",
  patient: {
    id: "pat_maya",
    displayName: "Maya Okafor",
    firstName: "Maya",
    procedure: "rhinoplasty",
    destinationCity: "Istanbul",
    destinationCountry: "Turkey",
  },
  clinic: {
    name: "Bosphorus Aesthetic Clinic",
    address: "Nisantasi, Istanbul",
    phone: "+905551112233",
  },
  hotel: {
    name: "Grand Pera Hotel",
    address: "Beyoglu, Istanbul",
    confirmationNumber: "GPH-442901",
  },
  transport: {
    driverName: "Emre Kaya",
    driverPhone: "+905554441212",
    nextPickupTitle: "Hotel pickup for clinic",
    nextPickupAt: "2026-06-12T23:30:00+03:00",
    nextPickupLocation: "Grand Pera Hotel lobby",
  },
  itinerary: [
    {
      id: "itin_departure",
      kind: "flight",
      title: "LAX departure",
      detail: "Depart for Istanbul",
      location: "Los Angeles International Airport",
      startsAt: "2026-06-09T21:00:00-07:00",
      endsAt: null,
      confirmationNumber: "TK-2187",
      driverName: null,
      driverPhone: null,
      sortOrder: 1,
      sourceDocumentId: "doc_maya_itinerary",
    },
    {
      id: "itin_clinic_pickup",
      kind: "transport",
      title: "Hotel pickup for clinic",
      detail: "Meet your driver in the hotel lobby.",
      location: "Grand Pera Hotel lobby",
      startsAt: "2026-06-12T23:30:00+03:00",
      endsAt: null,
      confirmationNumber: "DRV-98311",
      driverName: "Emre Kaya",
      driverPhone: "+905554441212",
      sortOrder: 2,
      sourceDocumentId: "doc_maya_itinerary",
    },
    {
      id: "itin_procedure",
      kind: "clinic",
      title: "Procedure",
      detail: "Morning procedure window; clinic team confirms exact time.",
      location: "Bosphorus Aesthetic Clinic",
      startsAt: "2026-06-13T08:00:00+03:00",
      endsAt: null,
      confirmationNumber: "BAC-1306",
      driverName: null,
      driverPhone: null,
      sortOrder: 3,
      sourceDocumentId: "doc_maya_itinerary",
    },
    {
      id: "itin_airport_pickup",
      kind: "transport",
      title: "Hotel pickup for airport",
      detail: "Airport transfer to SAW.",
      location: "Grand Pera Hotel lobby",
      startsAt: "2026-06-19T10:00:00+03:00",
      endsAt: null,
      confirmationNumber: "DRV-11920",
      driverName: "Emre Kaya",
      driverPhone: "+905554441212",
      sortOrder: 4,
      sourceDocumentId: "doc_maya_itinerary",
    },
  ],
  documents: [
    {
      id: "doc_maya_itinerary",
      title: "Maya Okafor itinerary packet",
      kind: "itinerary_packet",
      sourceType: "clinic_packet",
      sourceStatus: "verified",
      fileName: "maya-okafor-itinerary.pdf",
      contentType: "application/pdf",
      downloadable: false,
      relatedEventIds: [
        "itin_departure",
        "itin_clinic_pickup",
        "itin_procedure",
        "itin_airport_pickup",
      ],
    },
    {
      id: "doc_maya_preop",
      title: "Rhinoplasty pre-op packet",
      kind: "care_packet",
      sourceType: "clinic_packet",
      sourceStatus: "verified",
      fileName: "maya-okafor-preop.pdf",
      contentType: "application/pdf",
      downloadable: false,
      relatedEventIds: ["itin_procedure"],
    },
  ],
  sources: ["Maya Okafor itinerary packet", "Rhinoplasty pre-op packet"],
};
